import type { Metadata } from "next";
import Link from "next/link";
import { ArrowButton, Eyebrow, SiteShell } from "../components/site-shell";
import { NexoraFerrofluid } from "../components/nexora-ferrofluid";
import { LightSectionGrid } from "../components/nexora-interactions";

export const metadata: Metadata = { title: "Start a project", description: "Start a conversation with Nexora about your next digital decision." };

export default function StartProjectPage() {
  return <SiteShell><main><section className="start-hero"><NexoraFerrofluid /><div className="container start-grid"><div><Eyebrow light>Start a project</Eyebrow><h1>Tell us what you are trying to make clearer.</h1><p className="hero-lead">You do not need a perfect brief. Share the business context, the decision in front of you, or the part of your digital system that is not working yet.</p><div className="button-row"><Link className="button shimmer-button" href="mailto:info@nexoradm.ca?subject=Nexora%20project%20conversation"><span className="shimmer-button__content">Email Nexora <span className="button-arrow">↗</span></span></Link><Link className="quiet-link" href="/services/business-consultation">Not sure where to start? <span>See consultation</span> ↗</Link></div></div><div className="start-card"><span>Useful context</span><h2>What are you trying to do?</h2><ul><li><i>01</i><span>Build a clearer website or digital presence</span></li><li><i>02</i><span>Improve search visibility or paid growth</span></li><li><i>03</i><span>Define a brand system or product direction</span></li><li><i>04</i><span>Decide what to do next before spending more</span></li></ul></div></div></section><section className="section section-light start-detail"><LightSectionGrid /><div className="container"><div className="section-heading"><Eyebrow>What happens next</Eyebrow><h2>A simple conversation, then a clearer next phase.</h2></div><div className="start-steps"><article><span>01</span><h3>Share the context</h3><p>Send a short note with what the business does, what changed, and what you are considering.</p></article><article><span>02</span><h3>Clarify the real priority</h3><p>We look at the decision behind the request and the system it needs to fit into.</p></article><article><span>03</span><h3>Choose the right next move</h3><p>You leave with a clearer direction for the right project, sequence, or conversation.</p></article></div></div></section><section className="section start-bottom"><div className="container start-bottom-grid"><div><Eyebrow light>Prefer a direct note?</Eyebrow><h2>info@nexoradm.ca</h2><p>We’re based in Vancouver, BC and work across service businesses, growth teams, and ambitious digital products.</p></div><ArrowButton href="mailto:info@nexoradm.ca?subject=Start%20a%20Nexora%20project">Send an email</ArrowButton></div></section></main></SiteShell>;
}
