export type Service = {
  slug: string;
  code: string;
  category: string;
  title: string;
  description: string;
  quickIntro: string;
  quick: { label: string; detail: string; anchor: string }[];
  problemTitle: string;
  problems: { title: string; problem: string; solution: string; outcome: string }[];
  includedTitle: string;
  includedIntro: string;
  deliverables: { title: string; detail: string }[];
  processTitle: string;
  processIntro: string;
  process: { title: string; detail: string; tags: string[] }[];
  outcomesTitle: string;
  outcomes: { title: string; detail: string }[];
  faq: { question: string; answer: string }[];
  related: string[];
};

export const services: Service[] = [
  {
    slug: "web-design-development",
    code: "WD",
    category: "Web Design & Development",
    title: "Premium websites built for clarity, trust, and growth.",
    description: "We plan, design, and develop websites that explain your offer, build trust, support search, and make the next action easier to take.",
    quickIntro: "A complete website system starts with structure. Use this map to see where Nexora creates clarity before the pixels arrive.",
    quick: [
      { label: "UX Page Structure", detail: "Plan the pages, hierarchy, and flow around real business goals.", anchor: "included" },
      { label: "Website Design", detail: "Create a premium visual system that stays focused on the message.", anchor: "included" },
      { label: "WordPress Development", detail: "Turn the approved direction into a manageable, scalable build.", anchor: "process" },
      { label: "SEO-Ready Structure", detail: "Build headings, content flow, and internal links with search in mind.", anchor: "outcomes" },
      { label: "Conversion Path", detail: "Make the important next step visible and easy to understand.", anchor: "solves" },
    ],
    problemTitle: "Most websites do not fail because they look bad. They fail because they are unclear.",
    problems: [
      { title: "Your website looks fine, but does not explain enough.", problem: "Visitors still have to work out what you do, who you help, and why it matters.", solution: "We turn the offer into a clearer page structure and message hierarchy.", outcome: "People understand the business faster." },
      { title: "The design is not built around conversion.", problem: "Important actions are buried in a page that has no clear decision path.", solution: "We map the journey from first impression to qualified inquiry.", outcome: "The site gives visitors a more confident next move." },
      { title: "The website was not planned with SEO in mind.", problem: "Beautiful pages are disconnected from how people actually search.", solution: "We connect content, headings, page roles, and internal links from the start.", outcome: "The structure is ready for visibility work." },
    ],
    includedTitle: "A complete website system, not just a polished homepage.",
    includedIntro: "Clear deliverables without confusing agency language. The right scope is visible before development begins.",
    deliverables: [
      { title: "UX Page Structure", detail: "Page map, hierarchy, content flow, and key user journeys." },
      { title: "Website Design", detail: "Responsive layouts, visual language, components, and interaction direction." },
      { title: "WordPress Development", detail: "A manageable build that can support future pages and content." },
      { title: "SEO-Ready Structure", detail: "Search-aware headings, page roles, content relationships, and internal linking." },
      { title: "Conversion Path", detail: "Clear CTA placement and a smoother route to inquiry or booking." },
      { title: "Launch Support", detail: "Review, refinements, and direction for the next stage after launch." },
    ],
    processTitle: "A clear system before design begins.",
    processIntro: "Diagnose the current situation, create the right structure, and build a website that can improve over time.",
    process: [
      { title: "Diagnose", detail: "Review the business, audience, offer, current site, and conversion gaps.", tags: ["Business", "Audience", "Current Site"] },
      { title: "Structure", detail: "Define page roles, content hierarchy, user journeys, and priority actions.", tags: ["Page Map", "UX Flow", "Content"] },
      { title: "Design", detail: "Create the interface system, layouts, responsive behavior, and visual direction.", tags: ["UI System", "Layouts", "Responsive"] },
      { title: "Develop", detail: "Translate the approved direction into a working, manageable website.", tags: ["Build", "CMS", "Quality"] },
      { title: "Launch & Improve", detail: "Review performance, gather feedback, and plan the next useful improvements.", tags: ["Launch", "Review", "Care"] },
    ],
    outcomesTitle: "Built for trust, search, and conversion.",
    outcomes: [
      { title: "Clear Before Clever", detail: "The website explains the offer before it tries to impress." },
      { title: "Search-Aware From the Start", detail: "Structure supports future SEO and content growth." },
      { title: "Premium Without Noise", detail: "Less clutter makes the important message easier to see." },
      { title: "Built to Grow", detail: "Future pages and campaigns can fit into the same system." },
    ],
    faq: [
      { question: "Do you design and develop the website?", answer: "Yes. Nexora can carry the project from strategy and UX through visual design, development, review, and launch direction." },
      { question: "Can you redesign an existing website?", answer: "Yes. We review the current site first, then rebuild the structure, design, and experience around clearer goals." },
      { question: "Is SEO included?", answer: "Basic SEO-ready structure is included. Full SEO strategy, keyword planning, and ongoing optimization can be handled as a connected service." },
    ],
    related: ["seo-local-visibility", "brand-systems", "website-care"],
  },
  {
    slug: "seo-local-visibility",
    code: "SE",
    category: "SEO & Local Visibility",
    title: "Search visibility built for people already looking for your services.",
    description: "We build a clearer SEO foundation around structure, search intent, local relevance, and a roadmap your team can actually use.",
    quickIntro: "Search visibility should not depend on guesswork. See the foundation, relevance, and improvement areas that connect the system.",
    quick: [
      { label: "Visibility Gaps", detail: "Find where your business is missing from high-intent searches.", anchor: "solves" },
      { label: "Website SEO Structure", detail: "Clarify the page hierarchy that search engines and people need.", anchor: "included" },
      { label: "Local Visibility", detail: "Strengthen the signals that help nearby customers trust and find you.", anchor: "outcomes" },
      { label: "Content & Intent", detail: "Align pages with the questions and services people search for.", anchor: "included" },
      { label: "Visibility Roadmap", detail: "Prioritize what to fix first, next, and later.", anchor: "process" },
    ],
    problemTitle: "Search visibility should not depend on guesswork.",
    problems: [
      { title: "Your business is not showing up where customers search.", problem: "Search demand exists, but your pages and local signals are not aligned with it.", solution: "We identify the gaps between your offer, pages, and search intent.", outcome: "Visibility work starts with the right foundation." },
      { title: "Your service pages are not clear enough.", problem: "A page can contain keywords but still fail to explain the service convincingly.", solution: "We structure pages around user questions, intent, proof, and action.", outcome: "Search traffic has a clearer path to conversion." },
      { title: "SEO work feels random or disconnected.", problem: "Tasks happen without a shared priority or a sense of what matters next.", solution: "We turn findings into an ordered visibility roadmap.", outcome: "Your team can make better SEO decisions." },
    ],
    includedTitle: "SEO built around structure, search intent, and local relevance.",
    includedIntro: "A clearer SEO system, not random optimization tasks. We make the foundation visible before trying to scale it.",
    deliverables: [
      { title: "SEO Visibility Audit", detail: "Review technical, structural, content, and local visibility gaps." },
      { title: "Keyword & Intent Mapping", detail: "Connect services and content opportunities to real search intent." },
      { title: "Website Structure Direction", detail: "Clarify page roles, topic relationships, headings, and internal links." },
      { title: "Local Visibility Direction", detail: "Improve the trust signals that help location-based discovery." },
      { title: "On-Page Optimization", detail: "Make priority pages clearer for search engines and users." },
      { title: "Reporting & Recommendations", detail: "Turn what we learn into understandable next actions." },
    ],
    processTitle: "Fix the foundation before trying to scale visibility.",
    processIntro: "A practical path from audit to a more relevant, more useful presence in search.",
    process: [
      { title: "Audit", detail: "Review current visibility, structure, pages, local signals, and competitors.", tags: ["Gaps", "Pages", "Signals"] },
      { title: "Map", detail: "Connect search intent, services, locations, and content opportunities.", tags: ["Intent", "Services", "Topics"] },
      { title: "Optimize", detail: "Improve priority pages and the relationships between them.", tags: ["On-Page", "Links", "Clarity"] },
      { title: "Strengthen Local Signals", detail: "Build a more complete, trustworthy local presence.", tags: ["Local", "Trust", "Relevance"] },
      { title: "Improve Over Time", detail: "Use performance and new opportunities to plan the next cycle.", tags: ["Measure", "Learn", "Prioritize"] },
    ],
    outcomesTitle: "Built for search visibility, local trust, and long-term relevance.",
    outcomes: [
      { title: "Search Intent Before Keywords", detail: "Pages answer the real reason someone is searching." },
      { title: "Structure Before Content", detail: "The foundation keeps content from becoming disconnected." },
      { title: "Local Trust Signals", detail: "Location-based visibility has stronger supporting context." },
      { title: "Ongoing Improvement", detail: "SEO becomes a sequence of useful decisions, not a one-off task." },
    ],
    faq: [
      { question: "How quickly can SEO results happen?", answer: "Timing depends on the current foundation, competition, market, and the consistency of implementation. We start by making the priority path clear." },
      { question: "Do you handle local SEO?", answer: "Yes. Local visibility, service-area clarity, and trust signals are part of the SEO direction where they matter to the business." },
      { question: "Do you write all the content?", answer: "We can provide content direction, page structure, and recommendations. The exact writing scope is defined around the project." },
    ],
    related: ["web-design-development", "google-ads", "digital-strategy"],
  },
  {
    slug: "google-ads",
    code: "GA",
    category: "Google Ads",
    title: "Paid campaigns built for better leads, not just more clicks.",
    description: "We connect campaign strategy, search intent, landing pages, measurement, and optimization so your budget has a clearer job to do.",
    quickIntro: "The campaign system behind better paid traffic. Every part should support the same conversion outcome.",
    quick: [
      { label: "Campaign Strategy", detail: "Set the role, scope, and priorities before budget scales.", anchor: "included" },
      { label: "Keywords & Intent", detail: "Separate useful demand from traffic that only looks busy.", anchor: "solves" },
      { label: "Landing Page Alignment", detail: "Make the click lead to a page that continues the same message.", anchor: "included" },
      { label: "Conversion Tracking", detail: "Create a clearer view of what is producing useful action.", anchor: "process" },
      { label: "Ongoing Optimization", detail: "Use evidence to refine, pause, and scale responsibly.", anchor: "outcomes" },
    ],
    problemTitle: "Google Ads should bring better opportunities, not just more traffic.",
    problems: [
      { title: "Your ads spend money, but do not bring the right leads.", problem: "The campaign attracts attention without matching the real service or customer need.", solution: "We connect targeting, message, intent, and destination page.", outcome: "The campaign is built around qualified opportunity." },
      { title: "The campaign structure is too broad.", problem: "Budget and data are spread across terms and audiences with different jobs.", solution: "We organize campaigns around clearer intent and service priorities.", outcome: "Budget becomes easier to control." },
      { title: "You cannot clearly see what is working.", problem: "Without reliable conversion direction, optimization becomes guesswork.", solution: "We define the measurement path before trying to scale spend.", outcome: "Decisions are grounded in better signals." },
    ],
    includedTitle: "A clearer paid campaign system, not vague ad management.",
    includedIntro: "We make the relationship between the ad, the search, the page, and the action easier to understand.",
    deliverables: [
      { title: "Campaign Strategy", detail: "Goals, campaign roles, priorities, and budget direction." },
      { title: "Keyword & Intent Planning", detail: "Search themes organized around service and customer intent." },
      { title: "Ad Copy & Extensions", detail: "Messages designed to make relevance clear before the click." },
      { title: "Landing Page Alignment", detail: "Review the destination experience so it supports the campaign promise." },
      { title: "Conversion Tracking Direction", detail: "Define the actions that matter and how they should be read." },
      { title: "Ongoing Optimization", detail: "Prioritized changes based on performance and business value." },
    ],
    processTitle: "A clear system before budget scales.",
    processIntro: "Diagnose the opportunity, build the right structure, measure the right action, and improve with discipline.",
    process: [
      { title: "Diagnose", detail: "Review the offer, market, existing account, landing pages, and conversion path.", tags: ["Offer", "Account", "Page"] },
      { title: "Plan", detail: "Set campaign roles, intent groups, message direction, and budget priorities.", tags: ["Intent", "Budget", "Plan"] },
      { title: "Build", detail: "Create the campaign structure, copy direction, and aligned destination path.", tags: ["Campaigns", "Ads", "Pages"] },
      { title: "Measure", detail: "Review the signals that indicate qualified action, not just activity.", tags: ["Tracking", "Leads", "Quality"] },
      { title: "Optimize", detail: "Use learnings to refine targeting, messages, pages, and spend.", tags: ["Refine", "Test", "Scale"] },
    ],
    outcomesTitle: "Built for qualified leads, not just clicks.",
    outcomes: [
      { title: "Intent Before Traffic", detail: "Campaigns are organized around why people search." },
      { title: "Landing Page Alignment", detail: "The post-click experience continues the same promise." },
      { title: "Tracking Before Scaling", detail: "Measurement comes before confident budget decisions." },
      { title: "Budget Discipline", detail: "Spend is connected to priorities that can be reviewed." },
    ],
    faq: [
      { question: "Do you guarantee a specific number of leads?", answer: "No. We build and improve the system around the market, offer, landing experience, and data available. No responsible partner can guarantee a fixed outcome." },
      { question: "Can you help if the account already exists?", answer: "Yes. We can review an existing account and focus the next phase on the clearest opportunities." },
      { question: "Do you build landing pages too?", answer: "Yes. Landing page alignment can connect with Nexora Web Design & Development when the campaign needs a stronger destination." },
    ],
    related: ["web-design-development", "seo-local-visibility", "digital-strategy"],
  },
  {
    slug: "digital-strategy",
    code: "DS",
    category: "Digital Strategy",
    title: "A clear digital roadmap before you build, spend, or scale.",
    description: "We connect business direction, website and funnel priorities, SEO, paid growth, and execution into one practical roadmap.",
    quickIntro: "Digital growth gets easier to manage when the channels are connected by the same priorities.",
    quick: [
      { label: "Business & Offer Clarity", detail: "Make the business direction and offer easier to understand.", anchor: "solves" },
      { label: "Website & Funnel Direction", detail: "Connect the website experience to the action you need.", anchor: "included" },
      { label: "SEO & Content Priorities", detail: "Choose content and visibility work with a reason behind it.", anchor: "included" },
      { label: "Paid Growth Direction", detail: "Define when paid growth makes sense and what it should support.", anchor: "included" },
      { label: "Roadmap & Execution Path", detail: "Sequence the work into what to do first, next, and later.", anchor: "process" },
    ],
    problemTitle: "Most digital growth problems start with unclear priorities.",
    problems: [
      { title: "Your marketing feels disconnected.", problem: "Website, content, ads, and brand decisions each move in a different direction.", solution: "We connect the parts around one shared business and customer path.", outcome: "The digital system feels more intentional." },
      { title: "You are not sure what to fix first.", problem: "Everything sounds important, so nothing has a clear place in the sequence.", solution: "We prioritize the highest-leverage decisions before execution.", outcome: "Your team has a next move it can act on." },
      { title: "You are spending before the direction is clear.", problem: "Budget gets committed before the offer, page, measurement, or priorities are ready.", solution: "We make the foundation visible before recommending scale.", outcome: "Execution starts with less avoidable waste." },
    ],
    includedTitle: "From scattered ideas to a connected digital roadmap.",
    includedIntro: "A practical strategy direction, not just general advice. The goal is a sequence your business can use.",
    deliverables: [
      { title: "Business Positioning Direction", detail: "Clarify the offer, audience, differentiators, and message priorities." },
      { title: "Website & Conversion Flow", detail: "Map how the digital experience should explain and move people." },
      { title: "SEO & Content Priorities", detail: "Choose the visibility and content work that supports the strategy." },
      { title: "Paid Campaign Direction", detail: "Define the role of paid growth and the conditions for scaling." },
      { title: "Channel Alignment", detail: "Connect brand, website, search, content, and campaigns." },
      { title: "Roadmap & Action Plan", detail: "Organize what to do first, next, later, and why." },
    ],
    processTitle: "Clarity first. Priorities next. Execution after.",
    processIntro: "Diagnose the current state, clarify the offer, prioritize the work, and guide the next phase.",
    process: [
      { title: "Diagnose", detail: "Review business direction, audience, offer, channels, and current performance.", tags: ["Business", "Audience", "Channels"] },
      { title: "Clarify", detail: "Turn what is unclear into a sharper positioning and customer direction.", tags: ["Offer", "Message", "Customer"] },
      { title: "Prioritize", detail: "Identify the few decisions that will create the most useful momentum.", tags: ["Impact", "Effort", "Order"] },
      { title: "Map", detail: "Build the connected roadmap across website, content, search, and paid growth.", tags: ["Website", "SEO", "Paid"] },
      { title: "Guide Execution", detail: "Translate the roadmap into practical next steps and ownership.", tags: ["Actions", "Owners", "Review"] },
    ],
    outcomesTitle: "Built for clear priorities, not random marketing.",
    outcomes: [
      { title: "Direction Before Execution", detail: "The business knows what the next phase is for." },
      { title: "Channels Working Together", detail: "Each part has a role in the wider system." },
      { title: "Priorities You Can Act On", detail: "Strategy becomes a sequence, not a presentation." },
      { title: "Designed for Better Decisions", detail: "The roadmap stays useful as conditions change." },
    ],
    faq: [
      { question: "Is this a marketing plan or a business consultation?", answer: "Digital Strategy focuses on how your digital system should work together. Business Consultation is broader and is useful when the next business decision itself is still unclear." },
      { question: "Do you also implement the roadmap?", answer: "Yes. Nexora can continue into web, SEO, paid, brand, or care work when that is the right next phase." },
      { question: "Is there a fixed template for the roadmap?", answer: "The output is tailored to the business, but it is always organized around clear priorities, sequence, and next actions." },
    ],
    related: ["business-consultation", "web-design-development", "google-ads"],
  },
  {
    slug: "brand-systems",
    code: "BS",
    category: "Brand Systems",
    title: "A consistent brand system for every digital touchpoint.",
    description: "We create a usable brand system for websites, social media, ads, content, and campaigns so the business looks and sounds connected.",
    quickIntro: "A brand system works best when visuals, messaging, website design, social media, and campaigns feel connected.",
    quick: [
      { label: "Brand Direction", detail: "Define the overall visual and communication direction.", anchor: "solves" },
      { label: "Visual Identity System", detail: "Organize color, type, layout, imagery, and logo use.", anchor: "included" },
      { label: "Messaging Consistency", detail: "Clarify how the brand should sound and what it should communicate.", anchor: "included" },
      { label: "Digital Touchpoints", detail: "Translate the system across website, social, ads, and content.", anchor: "outcomes" },
      { label: "Brand System Map", detail: "Create a usable direction for future digital work.", anchor: "process" },
    ],
    problemTitle: "A brand should feel consistent wherever people meet it.",
    problems: [
      { title: "Your brand looks different everywhere.", problem: "Website, social, ads, documents, and visuals do not feel like the same business.", solution: "We define a consistent visual system for the digital channels that matter.", outcome: "The business feels more professional and recognizable." },
      { title: "The brand message is not clear enough.", problem: "People see the business but do not quickly understand what it does or why it matters.", solution: "We clarify the core message, tone, and communication direction.", outcome: "The brand becomes easier to understand and remember." },
      { title: "Design decisions keep changing.", problem: "Every post, page, ad, or graphic becomes a new design decision.", solution: "We create reusable rules that reduce visual guesswork.", outcome: "Future creative work becomes faster and more consistent." },
    ],
    includedTitle: "A usable brand system, not just a logo file.",
    includedIntro: "The system connects visual identity, messaging, digital layouts, and content direction so the brand can scale.",
    deliverables: [
      { title: "Brand Direction", detail: "Overall look, feel, tone, visual personality, and digital direction." },
      { title: "Logo Usage Direction", detail: "Practical guidance for how the logo should appear across materials." },
      { title: "Color & Typography System", detail: "Brand colors and typography organized for consistency." },
      { title: "Visual Style Guide", detail: "Layout style, image direction, icon language, spacing, and mood." },
      { title: "Messaging & Tone Direction", detail: "How the brand should communicate across key digital touchpoints." },
      { title: "Digital Asset Direction", detail: "Website sections, social templates, ad visuals, and content graphics." },
    ],
    processTitle: "Discover. Define. Systemize. Apply. Guide.",
    processIntro: "Before designing brand assets, we define where the brand needs to work and how it should stay consistent.",
    process: [
      { title: "Discover", detail: "Review the business, audience, competitors, existing visuals, and brand gaps.", tags: ["Business", "Audience", "Competitors"] },
      { title: "Define", detail: "Clarify the brand direction, message, tone, visual personality, and use cases.", tags: ["Message", "Tone", "Use Cases"] },
      { title: "Systemize", detail: "Organize logo use, colors, type, layouts, imagery, and design rules.", tags: ["Logo", "Colors", "Typography"] },
      { title: "Apply", detail: "Translate the system into website, social, ads, and content touchpoints.", tags: ["Website", "Social", "Ads"] },
      { title: "Guide", detail: "Prepare guidance so future design and marketing work stays consistent.", tags: ["Rules", "Templates", "Direction"] },
    ],
    outcomesTitle: "Built for consistency, recognition, and digital growth.",
    outcomes: [
      { title: "Consistency Across Channels", detail: "The business feels connected wherever people meet it." },
      { title: "Clearer Brand Memory", detail: "A recognizable system makes the business easier to remember." },
      { title: "Faster Creative Decisions", detail: "Reusable direction reduces unnecessary design debates." },
      { title: "Stronger Digital Presence", detail: "The brand is ready to support websites, campaigns, and content." },
    ],
    faq: [
      { question: "Is Brand Systems the same as logo design?", answer: "No. A logo can be part of the system, but Brand Systems defines how the business looks, sounds, and shows up across digital work." },
      { question: "Can you work with an existing logo?", answer: "Yes. We can build a stronger, more usable direction around existing assets when they are still right for the business." },
      { question: "Will you create social media templates?", answer: "We can define the direction and key template needs so future social and campaign work stays consistent." },
    ],
    related: ["web-design-development", "digital-strategy", "google-ads"],
  },
  {
    slug: "website-care",
    code: "WC",
    category: "Website Care",
    title: "Keep your website updated, secure, and ready to grow.",
    description: "We help businesses keep websites maintained, updated, secure, and aligned with ongoing digital growth after launch.",
    quickIntro: "Website Care keeps the website useful after launch. See what Nexora helps monitor, update, fix, and improve.",
    quick: [
      { label: "Website Updates", detail: "Keep website components, content, and technical parts current.", anchor: "included" },
      { label: "Security & Backup Awareness", detail: "Support safer management, backups, and basic care practices.", anchor: "process" },
      { label: "Content & Small Changes", detail: "Keep minor text, image, page, and CTA changes moving.", anchor: "included" },
      { label: "Technical Health", detail: "Review issues that affect performance, usability, and reliability.", anchor: "solves" },
      { label: "Continuous Improvement", detail: "Identify practical improvements that keep the site useful.", anchor: "outcomes" },
    ],
    problemTitle: "A website should not be left unmanaged after launch.",
    problems: [
      { title: "Your website gets outdated over time.", problem: "Old content, missed updates, plugin issues, and technical changes slowly accumulate.", solution: "We help keep the site maintained, reviewed, and updated.", outcome: "The website stays more current and reliable." },
      { title: "Small changes keep getting delayed.", problem: "Text, image, page, or CTA changes wait because nobody has time to handle them.", solution: "We support minor changes that keep the site aligned with the business.", outcome: "The website reflects what the business offers today." },
      { title: "Technical issues are easy to ignore.", problem: "Broken links, layout issues, speed concerns, and mobile problems reduce trust over time.", solution: "We review common issues before they become larger problems.", outcome: "The website feels more stable and professional." },
    ],
    includedTitle: "Ongoing care that keeps the website useful after launch.",
    includedIntro: "Clear support without vague maintenance promises. The focus is practical upkeep, health, and improvement.",
    deliverables: [
      { title: "Website Updates", detail: "Routine website updates and current key components when needed." },
      { title: "Content Changes", detail: "Minor text, image, CTA, service, or page content updates." },
      { title: "Technical Fixes", detail: "Review and address common issues that affect usability or reliability." },
      { title: "Security & Backup Awareness", detail: "Support basic safer website management and backup practices." },
      { title: "Performance Review", detail: "Review page experience, mobile usability, and speed awareness." },
      { title: "Improvement Recommendations", detail: "Identify small changes that keep the website clearer and more useful." },
    ],
    processTitle: "Monitor. Update. Protect. Fix. Improve.",
    processIntro: "Website Care follows a simple ongoing system that keeps the right things visible.",
    process: [
      { title: "Review", detail: "Review the website’s current condition, recent changes, visible issues, and care needs.", tags: ["Health", "Changes", "Priorities"] },
      { title: "Update", detail: "Keep components, content, and key details current when needed.", tags: ["Content", "Components", "Current"] },
      { title: "Protect", detail: "Support safer management around backups, security checks, and access awareness.", tags: ["Backups", "Safety", "Access"] },
      { title: "Fix", detail: "Address common issues before they become larger trust or usability problems.", tags: ["Issues", "Mobile", "Reliability"] },
      { title: "Improve", detail: "Recommend small improvements that keep the website aligned with growth.", tags: ["Clarity", "Growth", "Next"] },
    ],
    outcomesTitle: "Built for stability, security, and continuous improvement.",
    outcomes: [
      { title: "Maintained After Launch", detail: "The website has a clear owner for ongoing attention." },
      { title: "Small Changes Stay Moving", detail: "Minor updates do not have to wait for a redesign." },
      { title: "Issues Are Easier to Catch", detail: "Regular review helps surface problems earlier." },
      { title: "Improvement Becomes Ongoing", detail: "The site can grow with the business instead of staying frozen." },
    ],
    faq: [
      { question: "Is Website Care the same as a full redesign?", answer: "No. Website Care supports updates, maintenance, small changes, technical health, and improvement direction. A redesign is a separate project when the foundation needs to change." },
      { question: "Do you provide emergency support?", answer: "Care plans are designed around ongoing support and agreed priorities. Emergency coverage should be defined clearly in the project scope." },
      { question: "Can you care for a website Nexora did not build?", answer: "Usually, yes. We first review the website’s current condition and access so the support scope is realistic." },
    ],
    related: ["web-design-development", "seo-local-visibility", "digital-strategy"],
  },
  {
    slug: "business-consultation",
    code: "BC",
    category: "Business Consultation",
    title: "Make better business decisions before you build, spend, or scale.",
    description: "We help clarify the situation, identify the real priority, and define a practical business action roadmap.",
    quickIntro: "A consultation should turn uncertainty into a clearer next move, not just add more advice to the pile.",
    quick: [
      { label: "Business Direction", detail: "Understand what the business is trying to change or achieve.", anchor: "solves" },
      { label: "Growth Priorities", detail: "Separate the important growth lever from the loudest idea.", anchor: "framework" },
      { label: "Service & Offer Clarity", detail: "Make the offer easier to explain, compare, and act on.", anchor: "included" },
      { label: "Digital & Marketing Decisions", detail: "Know what should happen before committing to execution.", anchor: "included" },
      { label: "Business Action Roadmap", detail: "Leave with a clear Now / Next / Later direction.", anchor: "roadmap" },
    ],
    problemTitle: "Most business problems get worse when decisions are made without clear priorities.",
    problems: [
      { title: "You know something needs to change, but not what comes first.", problem: "Too many possible actions compete for attention and budget.", solution: "We review the situation and define the decision that matters most now.", outcome: "The next move becomes easier to choose." },
      { title: "You are getting advice from too many directions.", problem: "Different opinions create more noise than confidence.", solution: "We connect the advice back to the business context and customer reality.", outcome: "The business has a more grounded point of view." },
      { title: "You are about to spend money without a clear plan.", problem: "A website, campaign, or product build starts before the goal is defined.", solution: "We make the desired outcome, priority, and sequence visible first.", outcome: "Execution starts with fewer avoidable assumptions." },
    ],
    includedTitle: "Review the situation. Clarify the priority. Define the next move.",
    includedIntro: "The output is an action roadmap that tells the business what to fix, build, improve, or delay.",
    deliverables: [
      { title: "Business Situation Review", detail: "A focused review of the current context, challenges, and opportunities." },
      { title: "Priority Definition", detail: "Clarify the decision or change with the highest practical value." },
      { title: "Offer & Message Direction", detail: "Make the service, offer, or business story easier to understand." },
      { title: "Digital Decision Guidance", detail: "Assess website, marketing, product, and growth decisions in context." },
      { title: "Risk & Trade-off View", detail: "Make the cost of waiting, rushing, or choosing visible." },
      { title: "Business Action Roadmap", detail: "Now / Next / Later steps with a practical execution direction." },
    ],
    processTitle: "The Nexora Consultation Framework.",
    processIntro: "A human, focused process that makes the business decision easier to see and act on.",
    process: [
      { title: "Understand", detail: "Listen to the context, goals, constraints, and the decision in front of you.", tags: ["Context", "Goals", "Constraints"] },
      { title: "Diagnose", detail: "Separate the visible symptom from the underlying business problem.", tags: ["Problem", "Cause", "Evidence"] },
      { title: "Prioritize", detail: "Decide what deserves attention now and what can wait.", tags: ["Now", "Next", "Later"] },
      { title: "Recommend", detail: "Translate the priority into a practical direction with clear trade-offs.", tags: ["Options", "Trade-offs", "Choice"] },
      { title: "Roadmap", detail: "Create the action path for what to fix, build, improve, or delay.", tags: ["Actions", "Sequence", "Ownership"] },
    ],
    outcomesTitle: "Built for better decisions, clearer priorities, and practical next steps.",
    outcomes: [
      { title: "Better Decisions Before Execution", detail: "Understand the choice before committing time or budget." },
      { title: "Priorities You Can Understand", detail: "The business can explain why something comes first." },
      { title: "Business and Digital Alignment", detail: "Digital work supports the real business direction." },
      { title: "Actionable, Not Theoretical", detail: "The conversation ends with a usable next-step path." },
    ],
    faq: [
      { question: "Is this only for businesses that are stuck?", answer: "No. It is also useful before a major website, marketing, product, or growth decision when you want to reduce uncertainty." },
      { question: "What do I receive after the consultation?", answer: "The exact output depends on the scope, but the goal is a clear summary of the priority, trade-offs, and recommended Now / Next / Later path." },
      { question: "Can the consultation lead into implementation?", answer: "Yes. When the next step is a Nexora service, the roadmap can connect directly into the right project." },
    ],
    related: ["digital-strategy", "web-design-development", "application-development"],
  },
  {
    slug: "application-development",
    code: "AD",
    category: "Application Development",
    title: "Custom applications built around real business workflows.",
    description: "We help businesses plan, design, and develop custom web or mobile applications that support real workflows and create better digital experiences.",
    quickIntro: "Application development works best when business workflow, user experience, product structure, and the development plan are connected from the beginning.",
    quick: [
      { label: "Product Planning", detail: "Turn the idea, business goal, and user needs into product direction.", anchor: "solves" },
      { label: "UX Flow & App Structure", detail: "Map the user journey and role of every important screen.", anchor: "included" },
      { label: "Interface Design", detail: "Design clean, usable screens that make the product easier to understand.", anchor: "included" },
      { label: "Development Direction", detail: "Define a build direction that can support future growth.", anchor: "process" },
      { label: "Product Roadmap", detail: "Stage the path from MVP to launch and future improvements.", anchor: "outcomes" },
    ],
    problemTitle: "Most app projects fail when the product is not clearly planned before development.",
    problems: [
      { title: "The idea is clear, but the product is not.", problem: "The concept exists, but screens, flows, features, and priority are still unclear.", solution: "We turn the idea into a product direction and screen structure.", outcome: "The app becomes easier to estimate, design, and build." },
      { title: "The workflow is still manual or messy.", problem: "The team relies on spreadsheets, messages, separate tools, or repetitive work.", solution: "We review where a product can reduce friction in the real workflow.", outcome: "The app supports operations instead of adding complexity." },
      { title: "Development starts without a clear roadmap.", problem: "Trying to build everything at once increases cost, delay, and confusion.", solution: "We divide the product into MVP, launch, and future improvement phases.", outcome: "Development moves forward with clearer priorities." },
    ],
    includedTitle: "Application experiences built around real users and real workflows.",
    includedIntro: "A clearer product direction before development gets expensive. We make the scope visible without burying you in technical language.",
    deliverables: [
      { title: "Product Strategy & Scope", detail: "Goals, users, workflows, feature priority, and first-build direction." },
      { title: "UX Flow & Screen Mapping", detail: "User journeys and the action each screen needs to support." },
      { title: "UI Design System", detail: "Components, layouts, states, and visual consistency for the product." },
      { title: "Custom Web Application", detail: "Direction for dashboards, portals, booking systems, and workflow tools." },
      { title: "Mobile App Direction", detail: "Mobile-first flows and interface direction when an app-style experience is needed." },
      { title: "Testing, Launch & Improvement", detail: "Prepare the product for review, launch, feedback, and the next phase." },
    ],
    processTitle: "Plan the product before building the code.",
    processIntro: "A clear path from idea to MVP, launch, and future growth.",
    process: [
      { title: "Discover", detail: "Understand the business need, users, workflow, and the job the product must do.", tags: ["Business", "Users", "Workflow"] },
      { title: "Structure", detail: "Define features, journeys, screens, states, and the first useful product scope.", tags: ["Features", "Flows", "Screens"] },
      { title: "Design", detail: "Create an interface direction that is clear, usable, and coherent.", tags: ["UI", "States", "System"] },
      { title: "Develop", detail: "Guide a build direction around the product structure and the future roadmap.", tags: ["Build", "MVP", "Scale"] },
      { title: "Test & Improve", detail: "Review the product, learn from use, and prioritize the next improvements.", tags: ["Test", "Launch", "Learn"] },
    ],
    outcomesTitle: "Built for usability, scalability, and business fit.",
    outcomes: [
      { title: "User Experience Before Features", detail: "The product starts with how people need to work." },
      { title: "Business Workflow Fit", detail: "The application supports real operations and decisions." },
      { title: "Build in Clear Phases", detail: "MVP and future improvements have a visible order." },
      { title: "Ready to Improve Over Time", detail: "The product can learn and evolve after launch." },
    ],
    faq: [
      { question: "Do you build web apps, mobile apps, or both?", answer: "The direction can cover custom web applications, portals, dashboards, workflow tools, and mobile-first experiences depending on the business need." },
      { question: "Do you start with an MVP?", answer: "Usually. A focused first release helps the team validate the product and avoid building unnecessary complexity too early." },
      { question: "Can you help if we already started development?", answer: "Yes. We can review the existing product direction, identify gaps, and clarify the next phase." },
    ],
    related: ["business-consultation", "web-design-development", "digital-strategy"],
  },
];

export const serviceBySlug = Object.fromEntries(services.map((service) => [service.slug, service])) as Record<string, Service>;

export const insights = [
  { title: "Why a Website Should Start With Structure, Not Visuals", category: "Website Planning", read: "6 min read", accent: "01" },
  { title: "What Local SEO Actually Needs Before Content Starts", category: "SEO & Local", read: "5 min read", accent: "02" },
  { title: "Why Google Ads Fail Without the Right Landing Page", category: "Paid Growth", read: "7 min read", accent: "03" },
  { title: "How to Know Which Digital Move Comes First", category: "Digital Strategy", read: "5 min read", accent: "04" },
  { title: "Why a Logo Alone Is Not a Brand System", category: "Brand Systems", read: "4 min read", accent: "05" },
  { title: "Why App Projects Need an MVP Roadmap", category: "Product Direction", read: "6 min read", accent: "06" },
  { title: "What Happens When a Website Is Left Unmanaged", category: "Website Care", read: "5 min read", accent: "07" },
  { title: "When a Business Needs Consultation Before Execution", category: "Business Decisions", read: "6 min read", accent: "08" },
];
