import Link from "next/link";
import { ArrowButton, Eyebrow, SiteShell } from "./components/site-shell";
import { insights, services } from "./data";

function SystemVisual() {
  return <div className="system-visual" aria-label="A visual map of connected digital systems">
    <div className="visual-orbit orbit-a" /><div className="visual-orbit orbit-b" /><div className="visual-core">NX</div>
    <div className="visual-card visual-card-top"><span>01 / direction</span><strong>Clearer priorities</strong><div className="visual-line wide" /><div className="visual-line" /></div>
    <div className="visual-card visual-card-bottom"><span>04 / momentum</span><strong>Built to improve</strong><div className="signal-row"><i /><i /><i /><i /><i /></div></div>
    <span className="visual-pill pill-one">Brand</span><span className="visual-pill pill-two">Website</span><span className="visual-pill pill-three">Growth</span>
  </div>;
}

export default function Home() {
  return <SiteShell><main>
    <section className="home-hero"><div className="hero-grid container"><div className="hero-copy"><Eyebrow light>Nexora Digital Marketing Inc.</Eyebrow><h1>Digital systems built with <em>strategy</em> before design.</h1><p className="hero-lead">We help businesses make clearer digital decisions, build stronger systems, and grow with more direction.</p><div className="button-row"><ArrowButton href="/start-project">Start a project</ArrowButton><ArrowButton href="#services" secondary>Explore services</ArrowButton></div><div className="hero-proof"><span>Strategy before design</span><span>Clearer decisions</span><span>Built to grow</span></div></div><SystemVisual /></div><div className="hero-scroll">Scroll to explore <span>↓</span></div></section>
    <section className="trust-strip"><div className="container trust-inner"><p>One connected digital system across the decisions that shape growth.</p><div><span>Web</span><span>Search</span><span>Paid</span><span>Brand</span><span>Product</span></div></div></section>
    <section className="section section-light" id="services"><div className="container"><div className="section-heading split-heading"><div><Eyebrow>What we build</Eyebrow><h2>Digital services connected by one clear growth system.</h2></div><p>Each service has a distinct role. Together, they help your business clarify, build, attract, and improve.</p></div><div className="service-grid">{services.slice(0, 6).map((service, index) => <Link className={`service-tile ${index % 3 === 1 ? "service-tile-blue" : ""}`} href={`/services/${service.slug}`} key={service.slug}><div className="tile-top"><span className="tile-code">{service.code}</span><span className="tile-arrow">↗</span></div><div><h3>{service.category}</h3><p>{service.title}</p></div><span className="tile-link">View service</span></Link>)}</div></div></section>
    <section className="section system-section"><div className="container system-layout"><div className="system-intro"><Eyebrow light>How Nexora works</Eyebrow><h2>Built with strategy before design.</h2><p>Strong digital work is less about adding more and more about making the right things connect.</p><ArrowButton href="/services/digital-strategy">See digital strategy</ArrowButton></div><div className="system-steps">{[{n:"01",t:"Clarify",d:"Understand the business, the customer, and the decision in front of you."},{n:"02",t:"Structure",d:"Turn priorities into a clearer page, product, brand, or campaign system."},{n:"03",t:"Build",d:"Create the right digital experience with the right level of complexity."},{n:"04",t:"Improve",d:"Use evidence and feedback to keep the system useful over time."}].map((step) => <article key={step.n}><span>{step.n}</span><div><h3>{step.t}</h3><p>{step.d}</p></div></article>)}</div></div></section>
    <section className="section section-light entry-section"><div className="container"><div className="section-heading"><Eyebrow>Two direct paths</Eyebrow><h2>Start with the decision you are trying to make.</h2></div><div className="entry-grid"><Link href="/services/business-consultation" className="entry-card entry-card-light"><span className="entry-kicker">Business Consultation</span><h3>Not sure what to do next?</h3><p>Review the situation, clarify the priority, and leave with a practical action roadmap.</p><span className="entry-cta">Find the next move <b>↗</b></span></Link><Link href="/services/application-development" className="entry-card entry-card-dark"><span className="entry-kicker">Application Development</span><h3>Need a custom digital product?</h3><p>Plan, design, and develop dashboards, portals, workflow tools, and product experiences around real business needs.</p><span className="entry-cta">Explore product direction <b>↗</b></span></Link></div></div></section>
    <section className="section work-section" id="work"><div className="container"><div className="section-heading split-heading"><div><Eyebrow light>Selected work</Eyebrow><h2>Digital work across service businesses.</h2></div><p>Keep the work focused on the business problem, the system behind it, and the outcome it supports.</p></div><div className="work-grid"><article className="work-card work-card-large"><div><span>Home Care / Website / Content Direction</span><h3>Trust Hands</h3><p>Non-medical home care presence with service clarity, family trust, and conversion-focused page direction.</p></div><div className="work-art work-art-home"><div className="art-window"><span /><span /><span /><strong>Care built around trust.</strong><i /><i /></div></div></article><article className="work-card"><div><span>Legal / Work Injury / SEO Structure</span><h3>Work Injury Advocates</h3><p>Clearer legal-service positioning around injury claims, representation, and trust-building.</p></div><div className="work-art work-art-legal"><div className="art-portrait" /></div></article><article className="work-card"><div><span>Local Service / Web / Visibility</span><h3>Cleaning & Driving</h3><p>Service pages designed around local clarity, visual trust, and customer action.</p></div><div className="work-art work-art-local"><div className="art-route"><i /><i /><i /></div></div></article></div></div></section>
    <section className="section insight-section"><div className="container"><div className="section-heading split-heading"><div><Eyebrow>Insights</Eyebrow><h2>Practical digital thinking.</h2></div><p>Useful perspective for clearer digital decisions — before you build, spend, or scale.</p></div><div className="insight-grid">{insights.slice(0, 3).map((item) => <Link href="/insights" className="insight-card" key={item.title}><span className="insight-number">{item.accent}</span><div><span className="insight-category">{item.category} · {item.read}</span><h3>{item.title}</h3></div><span className="insight-arrow">↗</span></Link>)}</div><Link className="text-link" href="/insights">View all insights <span>↗</span></Link></div></section>
    <section className="section final-section"><div className="container final-panel"><div><Eyebrow light>Start a project</Eyebrow><h2>Ready to build a clearer digital presence?</h2><p>Let’s plan the right website, visibility, content, brand system, application, or growth direction for your business.</p></div><ArrowButton href="/start-project">Start the conversation</ArrowButton></div></section>
  </main></SiteShell>;
}
